#!/usr/bin/perl
use strict;

use Getopt::Std;
use Sipwise::Provisioning::Billing;
use Sipwise::Provisioning::Config;

my %CONFIG = (admin => 'cmd');

my $config = Sipwise::Provisioning::Config->new()->get_config();

unless ($CONFIG{password} = $config->{acl}->{$CONFIG{admin}}->{password}) {
  die "Error: No provisioning password found for user $CONFIG{admin}\n";
}

my %BILLING = (
                billing_profile => 'default',
# not needed, but may be set if desired
#                product         => 'handle',
              );

sub main;
sub usage;
sub call_prov;

my %opts;
getopts('i:c:k:s:', \%opts);

die usage() unless defined $opts{i} and defined $opts{c};

my $file = $opts{c} or die "Need to get CSV file on the command line\n";
 
open(my $data, '<', $file) or die "Could not open '$file' $!\n";
 
my $bprov = Sipwise::Provisioning::Billing->new();

# clear list if -x
if(defined $opts{k}) {
        call_prov( 'set_ncos_pattern_list',
                   {
                     level         => $opts{i},
                     purge_existing => 1,
		     patterns => [],
                   }
                 );
        print "Cleared NCOS Level: $opts{i}.\n";
}



main;

sub main {

while (my $line = <$data>) {
  chomp $line;
 
  my @fields = split "," , $line;
  #strip non numeric
  $fields[0] =~ s/\D//g;
  #prefix/postfix for regex
  my $pfx = '^'.$fields[0].'.*';
  #pack the pattern
  my $pattern    = [{ description => $fields[1],
                       pattern   => $pfx,
                     }];


    if(defined $fields[0]) {
        call_prov( 'set_ncos_pattern_list',
                   {
                     level         => $opts{i},
                     patterns => $pattern,
                   }
                 );
        print "Added Pattern [$pfx] ($fields[1]) to NCOS Level: $opts{i}.\n";
    }



}

    exit;
}


sub call_prov {
    #   scalar,    hash-ref
    my ($function, $parameter) = @_;
    my $result;

    eval {
        $result = $bprov->handle_request( $function,
                                          {
                                            authentication => {
                                                                type     => 'system',
                                                                username => $CONFIG{admin},
                                                                password => $CONFIG{password},
                                                              },
                                            parameters => $parameter,
                                        });
    };

    if($@) {
        if(ref $@ eq 'SOAP::Fault') {
            die "Billing\::$function failed: ". $@->faultstring ."\n";
        } else {
            die "Billing\::$function failed: $@\n";
        }
    }

    return $result;
}

sub usage {
    die "Usage:\n$0 [-i NCOS_Level] -c <csv_input_file>\n\n".
        "e.g.: $0 -i BLOCKLIST -c test.csv\n\n".
        "Options:\n".
        "  -i <ncos_level>      NCOS Level name to use\n".
        "  -c <csv_input_file>  CSV with Patterns (pattern,description)\n".
        "  -x <1>               Clear NCOS List before inserting data\n".
        "";
}
